### PR TITLE
BrokerStorage to make sense

### PR DESCRIPTION
**Pull request by jakub-i**
So in my mind the BrokerStorage should implement the interafce specified above and the Students member should be made private as it would otherwise extend the interface specification. If not then maybe an explaination for it to be public should be added.
\Jakub

### CODE REVIEW

**Comment by hassanhabib** [comment]
@jakub-i just for validation. run an ef migration on a private `Students` db set and let me know if it still works.

**Comment by jakub-i** [comment]
> @jakub-i just for validation. run an ef migration on a private `Students` db set and let me know if it still works.

Hi @hassanhabib 
I was to quick there and did not spot the context in which the example was given, sorry. I will change that back.

\Jakub

**Comment by hassanhabib** [comment]
@jakub-i we might also not need to reference the interface in every partial class.
So there's `StorageBroker.cs` that's the file that has the reference to the interface `IStorageBroker`
but the other partials which branch off of the root file like `StorageBroker.Students.cs` might need to that extra extension or interface implementation.

**Comment by hassanhabib** [comment]
Closing due to inactivity

**Pull request closed without merging**
