### PR TITLE
DOCUMENTATION: Removed duplicate 404 entry

### PR DESCRIPTION
**Pull request by ShriHumrudha**

### CODE REVIEW

**Review by ElbekDeveloper — APPROVED** [review]

**Comment by hassanhabib** [comment]
@ShriHumrudha && @ElbekDeveloper we may need to keep both with a little justification to distinguish between Not Found as in the Url is not found and Not Found as in the entity is not found.

**Comment by ElbekDeveloper** [comment]
I got it. maybe we can change the name to UrlNotFound ?

**Comment by ShriHumrudha** [comment]
I am thinking URL Not found can be of two scenarios:
scenario 1 - a typo in the configuration to hit a wrong endpoint which should result in validation exception
scenario 2 - a valid URL but the dependency system is down / some failure at their end which should result in critical dependency exception (as we handle storage Connection exception). Even maybe depending on the system design, it can just land as a dependency exception too.

In case of entity not found, it might be tricky due to the upstream technology. Example: Cosmos DB as of today return 404 for everything and we do not have a way to differentiate between specific reasons - https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-not-found

**Comment by hassanhabib** [comment]
> I got it. maybe we can change the name to UrlNotFound ?

@ElbekDeveloper I'm okay with that option.
@ShriHumrudha do you concur?

Thank you both :)

**Pull request merged**
